// AUTO-GENERATED by scripts/build-messages.mjs — DO NOT EDIT.
// Source of truth: messages/<locale>.json. Run `pnpm build` (or
// `node scripts/build-messages.mjs`) to regenerate after editing the
// catalog. One named export per namespace keeps the per-widget bundles
// tree-shakeable (see the script header for the rationale).
/* eslint-disable */
import type { LocaleCatalog } from "./index";

export const common: LocaleCatalog = {
  "en": {
    "cancel": "Cancel",
    "save": "Save",
    "close": "Close",
    "copy": "Copy",
    "copied": "Copied!",
    "retry": "Retry",
    "previous": "Previous",
    "next": "Next",
    "never": "never",
    "dash": "—"
  },
  "de": {
    "cancel": "Abbrechen",
    "save": "Speichern",
    "close": "Schließen",
    "copy": "Kopieren",
    "copied": "Kopiert!",
    "retry": "Erneut versuchen",
    "previous": "Zurück",
    "next": "Weiter",
    "never": "nie",
    "dash": "—"
  },
  "fr": {
    "cancel": "Annuler",
    "save": "Enregistrer",
    "close": "Fermer",
    "copy": "Copier",
    "copied": "Copié !",
    "retry": "Réessayer",
    "previous": "Précédent",
    "next": "Suivant",
    "never": "jamais",
    "dash": "—"
  },
  "es": {
    "cancel": "Cancelar",
    "save": "Guardar",
    "close": "Cerrar",
    "copy": "Copiar",
    "copied": "¡Copiado!",
    "retry": "Reintentar",
    "previous": "Anterior",
    "next": "Siguiente",
    "never": "nunca",
    "dash": "—"
  },
  "ja": {
    "cancel": "キャンセル",
    "save": "保存",
    "close": "閉じる",
    "copy": "コピー",
    "copied": "コピーしました",
    "retry": "再試行",
    "previous": "前へ",
    "next": "次へ",
    "never": "なし",
    "dash": "—"
  },
  "pt-BR": {
    "cancel": "Cancelar",
    "save": "Salvar",
    "close": "Fechar",
    "copy": "Copiar",
    "copied": "Copiado!",
    "retry": "Tentar novamente",
    "previous": "Anterior",
    "next": "Próximo",
    "never": "nunca",
    "dash": "—"
  }
} as const;

export const ssoConnection: LocaleCatalog = {
  "en": {
    "title": "SSO connections",
    "subtitle": "Configure SAML or OIDC for this organization. Your changes apply instantly.",
    "newConnection": "New connection",
    "empty": "No SSO connections yet. Click \"{action}\" to add one.",
    "loading": "Loading connections…",
    "columns": {
      "provider": "Provider",
      "protocol": "Protocol",
      "status": "Status",
      "configured": "Configured"
    },
    "status": {
      "pending": "pending",
      "active": "active",
      "suspended": "suspended"
    },
    "actions": {
      "metadata": "Metadata",
      "test": "Test",
      "edit": "Edit",
      "delete": "Delete"
    },
    "deleteConfirm": "Delete the {provider} connection?",
    "form": {
      "provider": "Provider",
      "protocol": "Protocol",
      "displayName": "Display name (optional)",
      "displayNamePlaceholder": "Acme Okta production",
      "metadataXml": "IdP metadata XML",
      "oidcDiscovery": "OIDC discovery URL",
      "clientId": "Client ID",
      "clientSecret": "Client secret",
      "create": "Create connection",
      "saving": "Saving…"
    },
    "edit": {
      "title": "Edit {provider}",
      "displayName": "Display name"
    },
    "metadataPanel": {
      "title": "SP metadata",
      "download": "Download XML"
    }
  },
  "de": {
    "title": "SSO-Verbindungen",
    "subtitle": "Konfigurieren Sie SAML oder OIDC für diese Organisation. Ihre Änderungen werden sofort wirksam.",
    "newConnection": "Neue Verbindung",
    "empty": "Noch keine SSO-Verbindungen. Klicken Sie auf „{action}“, um eine hinzuzufügen.",
    "loading": "Verbindungen werden geladen…",
    "columns": {
      "provider": "Anbieter",
      "protocol": "Protokoll",
      "status": "Status",
      "configured": "Konfiguriert"
    },
    "status": {
      "pending": "ausstehend",
      "active": "aktiv",
      "suspended": "ausgesetzt"
    },
    "actions": {
      "metadata": "Metadaten",
      "test": "Testen",
      "edit": "Bearbeiten",
      "delete": "Löschen"
    },
    "deleteConfirm": "Die {provider}-Verbindung löschen?",
    "form": {
      "provider": "Anbieter",
      "protocol": "Protokoll",
      "displayName": "Anzeigename (optional)",
      "displayNamePlaceholder": "Acme Okta Produktion",
      "metadataXml": "IdP-Metadaten-XML",
      "oidcDiscovery": "OIDC-Discovery-URL",
      "clientId": "Client-ID",
      "clientSecret": "Client-Secret",
      "create": "Verbindung erstellen",
      "saving": "Wird gespeichert…"
    },
    "edit": {
      "title": "{provider} bearbeiten",
      "displayName": "Anzeigename"
    },
    "metadataPanel": {
      "title": "SP-Metadaten",
      "download": "XML herunterladen"
    }
  },
  "fr": {
    "title": "Connexions SSO",
    "subtitle": "Configurez SAML ou OIDC pour cette organisation. Vos modifications s’appliquent instantanément.",
    "newConnection": "Nouvelle connexion",
    "empty": "Aucune connexion SSO pour le moment. Cliquez sur « {action} » pour en ajouter une.",
    "loading": "Chargement des connexions…",
    "columns": {
      "provider": "Fournisseur",
      "protocol": "Protocole",
      "status": "Statut",
      "configured": "Configuré"
    },
    "status": {
      "pending": "en attente",
      "active": "actif",
      "suspended": "suspendu"
    },
    "actions": {
      "metadata": "Métadonnées",
      "test": "Tester",
      "edit": "Modifier",
      "delete": "Supprimer"
    },
    "deleteConfirm": "Supprimer la connexion {provider} ?",
    "form": {
      "provider": "Fournisseur",
      "protocol": "Protocole",
      "displayName": "Nom d’affichage (facultatif)",
      "displayNamePlaceholder": "Acme Okta production",
      "metadataXml": "XML de métadonnées IdP",
      "oidcDiscovery": "URL de découverte OIDC",
      "clientId": "ID client",
      "clientSecret": "Secret client",
      "create": "Créer la connexion",
      "saving": "Enregistrement…"
    },
    "edit": {
      "title": "Modifier {provider}",
      "displayName": "Nom d’affichage"
    },
    "metadataPanel": {
      "title": "Métadonnées SP",
      "download": "Télécharger le XML"
    }
  },
  "es": {
    "title": "Conexiones SSO",
    "subtitle": "Configura SAML u OIDC para esta organización. Tus cambios se aplican al instante.",
    "newConnection": "Nueva conexión",
    "empty": "Aún no hay conexiones SSO. Haz clic en «{action}» para añadir una.",
    "loading": "Cargando conexiones…",
    "columns": {
      "provider": "Proveedor",
      "protocol": "Protocolo",
      "status": "Estado",
      "configured": "Configurado"
    },
    "status": {
      "pending": "pendiente",
      "active": "activo",
      "suspended": "suspendido"
    },
    "actions": {
      "metadata": "Metadatos",
      "test": "Probar",
      "edit": "Editar",
      "delete": "Eliminar"
    },
    "deleteConfirm": "¿Eliminar la conexión de {provider}?",
    "form": {
      "provider": "Proveedor",
      "protocol": "Protocolo",
      "displayName": "Nombre para mostrar (opcional)",
      "displayNamePlaceholder": "Acme Okta producción",
      "metadataXml": "XML de metadatos del IdP",
      "oidcDiscovery": "URL de descubrimiento OIDC",
      "clientId": "ID de cliente",
      "clientSecret": "Secreto de cliente",
      "create": "Crear conexión",
      "saving": "Guardando…"
    },
    "edit": {
      "title": "Editar {provider}",
      "displayName": "Nombre para mostrar"
    },
    "metadataPanel": {
      "title": "Metadatos del SP",
      "download": "Descargar XML"
    }
  },
  "ja": {
    "title": "SSO 接続",
    "subtitle": "この組織の SAML または OIDC を設定します。変更は即時に反映されます。",
    "newConnection": "新しい接続",
    "empty": "SSO 接続はまだありません。「{action}」をクリックして追加してください。",
    "loading": "接続を読み込んでいます…",
    "columns": {
      "provider": "プロバイダー",
      "protocol": "プロトコル",
      "status": "ステータス",
      "configured": "設定日時"
    },
    "status": {
      "pending": "保留中",
      "active": "有効",
      "suspended": "停止中"
    },
    "actions": {
      "metadata": "メタデータ",
      "test": "テスト",
      "edit": "編集",
      "delete": "削除"
    },
    "deleteConfirm": "{provider} の接続を削除しますか？",
    "form": {
      "provider": "プロバイダー",
      "protocol": "プロトコル",
      "displayName": "表示名（任意）",
      "displayNamePlaceholder": "Acme Okta 本番",
      "metadataXml": "IdP メタデータ XML",
      "oidcDiscovery": "OIDC ディスカバリー URL",
      "clientId": "クライアント ID",
      "clientSecret": "クライアントシークレット",
      "create": "接続を作成",
      "saving": "保存しています…"
    },
    "edit": {
      "title": "{provider} を編集",
      "displayName": "表示名"
    },
    "metadataPanel": {
      "title": "SP メタデータ",
      "download": "XML をダウンロード"
    }
  },
  "pt-BR": {
    "title": "Conexões SSO",
    "subtitle": "Configure SAML ou OIDC para esta organização. Suas alterações são aplicadas instantaneamente.",
    "newConnection": "Nova conexão",
    "empty": "Ainda não há conexões SSO. Clique em \"{action}\" para adicionar uma.",
    "loading": "Carregando conexões…",
    "columns": {
      "provider": "Provedor",
      "protocol": "Protocolo",
      "status": "Status",
      "configured": "Configurado"
    },
    "status": {
      "pending": "pendente",
      "active": "ativo",
      "suspended": "suspenso"
    },
    "actions": {
      "metadata": "Metadados",
      "test": "Testar",
      "edit": "Editar",
      "delete": "Excluir"
    },
    "deleteConfirm": "Excluir a conexão {provider}?",
    "form": {
      "provider": "Provedor",
      "protocol": "Protocolo",
      "displayName": "Nome de exibição (opcional)",
      "displayNamePlaceholder": "Acme Okta produção",
      "metadataXml": "XML de metadados do IdP",
      "oidcDiscovery": "URL de descoberta OIDC",
      "clientId": "ID do cliente",
      "clientSecret": "Segredo do cliente",
      "create": "Criar conexão",
      "saving": "Salvando…"
    },
    "edit": {
      "title": "Editar {provider}",
      "displayName": "Nome de exibição"
    },
    "metadataPanel": {
      "title": "Metadados do SP",
      "download": "Baixar XML"
    }
  }
} as const;

export const directorySync: LocaleCatalog = {
  "en": {
    "title": "Directory sync",
    "subtitle": "Provision a SCIM 2.0 directory so user lifecycle (joiners, movers, leavers) stays in lockstep with this organization.",
    "provision": "Provision directory",
    "empty": "No directories yet. Click \"{action}\" to create one.",
    "loading": "Loading directories…",
    "columns": {
      "name": "Name",
      "provider": "Provider",
      "state": "State",
      "lastSync": "Last sync"
    },
    "state": {
      "active": "active",
      "paused": "paused",
      "revoked": "revoked"
    },
    "actions": {
      "users": "Users",
      "groups": "Groups",
      "syncNow": "Sync now",
      "rotateToken": "Rotate token",
      "delete": "Delete"
    },
    "deleteConfirm": "Delete the {name} directory? This stops SCIM sync immediately.",
    "form": {
      "displayName": "Display name",
      "displayNamePlaceholder": "Acme HQ Okta",
      "provider": "Provider",
      "provision": "Provision",
      "provisioning": "Provisioning…"
    },
    "secret": {
      "title": "Save these credentials",
      "done": "I've copied them",
      "warning": "We can't show this bearer token again. Paste it into your IdP's SCIM configuration immediately. If you lose it, rotate the token and re-paste.",
      "scimEndpoint": "SCIM endpoint",
      "bearerToken": "Bearer token"
    },
    "users": {
      "title": "{count, plural, =0 {Synced users} one {# synced user} other {# synced users}}",
      "loading": "Loading users…",
      "empty": "No users have synced yet. Provision a few in your IdP and click \"Sync now\".",
      "columns": {
        "email": "Email",
        "name": "Name",
        "status": "Status",
        "lastSynced": "Last synced"
      },
      "status": {
        "active": "active",
        "suspended": "suspended",
        "deactivated": "deactivated"
      }
    },
    "groups": {
      "title": "{count, plural, =0 {Synced groups} one {# synced group} other {# synced groups}}",
      "loading": "Loading groups…",
      "empty": "No groups have synced yet. Provision groups in your IdP to populate this list.",
      "columns": {
        "name": "Group",
        "members": "Members",
        "lastUpdated": "Last updated"
      }
    }
  },
  "de": {
    "title": "Verzeichnissynchronisierung",
    "subtitle": "Richten Sie ein SCIM-2.0-Verzeichnis ein, damit der Benutzerlebenszyklus (Eintritte, Wechsel, Austritte) mit dieser Organisation Schritt hält.",
    "provision": "Verzeichnis einrichten",
    "empty": "Noch keine Verzeichnisse. Klicken Sie auf „{action}“, um eines zu erstellen.",
    "loading": "Verzeichnisse werden geladen…",
    "columns": {
      "name": "Name",
      "provider": "Anbieter",
      "state": "Zustand",
      "lastSync": "Letzte Synchronisierung"
    },
    "state": {
      "active": "aktiv",
      "paused": "pausiert",
      "revoked": "widerrufen"
    },
    "actions": {
      "users": "Benutzer",
      "syncNow": "Jetzt synchronisieren",
      "rotateToken": "Token rotieren",
      "delete": "Löschen",
      "groups": "Gruppen"
    },
    "deleteConfirm": "Das Verzeichnis {name} löschen? Dadurch wird die SCIM-Synchronisierung sofort gestoppt.",
    "form": {
      "displayName": "Anzeigename",
      "displayNamePlaceholder": "Acme HQ Okta",
      "provider": "Anbieter",
      "provision": "Einrichten",
      "provisioning": "Wird eingerichtet…"
    },
    "secret": {
      "title": "Speichern Sie diese Zugangsdaten",
      "done": "Ich habe sie kopiert",
      "warning": "Wir können dieses Bearer-Token nicht erneut anzeigen. Fügen Sie es sofort in die SCIM-Konfiguration Ihres IdP ein. Falls Sie es verlieren, rotieren Sie das Token und fügen es erneut ein.",
      "scimEndpoint": "SCIM-Endpunkt",
      "bearerToken": "Bearer-Token"
    },
    "users": {
      "title": "{count, plural, =0 {Synchronisierte Benutzer} one {# synchronisierter Benutzer} other {# synchronisierte Benutzer}}",
      "loading": "Benutzer werden geladen…",
      "empty": "Es wurden noch keine Benutzer synchronisiert. Richten Sie einige in Ihrem IdP ein und klicken Sie auf „Jetzt synchronisieren“.",
      "columns": {
        "email": "E-Mail",
        "name": "Name",
        "status": "Status",
        "lastSynced": "Zuletzt synchronisiert"
      },
      "status": {
        "active": "aktiv",
        "suspended": "ausgesetzt",
        "deactivated": "deaktiviert"
      }
    },
    "groups": {
      "title": "{count, plural, =0 {Synchronisierte Gruppen} one {# synchronisierte Gruppe} other {# synchronisierte Gruppen}}",
      "loading": "Gruppen werden geladen…",
      "empty": "Noch keine Gruppen synchronisiert. Legen Sie Gruppen in Ihrem IdP an, um diese Liste zu füllen.",
      "columns": {
        "name": "Gruppe",
        "members": "Mitglieder",
        "lastUpdated": "Zuletzt aktualisiert"
      }
    }
  },
  "fr": {
    "title": "Synchronisation d’annuaire",
    "subtitle": "Provisionnez un annuaire SCIM 2.0 pour que le cycle de vie des utilisateurs (arrivées, mutations, départs) reste aligné avec cette organisation.",
    "provision": "Provisionner un annuaire",
    "empty": "Aucun annuaire pour le moment. Cliquez sur « {action} » pour en créer un.",
    "loading": "Chargement des annuaires…",
    "columns": {
      "name": "Nom",
      "provider": "Fournisseur",
      "state": "État",
      "lastSync": "Dernière synchronisation"
    },
    "state": {
      "active": "actif",
      "paused": "en pause",
      "revoked": "révoqué"
    },
    "actions": {
      "users": "Utilisateurs",
      "syncNow": "Synchroniser maintenant",
      "rotateToken": "Renouveler le jeton",
      "delete": "Supprimer",
      "groups": "Groupes"
    },
    "deleteConfirm": "Supprimer l’annuaire {name} ? Cela arrête immédiatement la synchronisation SCIM.",
    "form": {
      "displayName": "Nom d’affichage",
      "displayNamePlaceholder": "Acme HQ Okta",
      "provider": "Fournisseur",
      "provision": "Provisionner",
      "provisioning": "Provisionnement…"
    },
    "secret": {
      "title": "Enregistrez ces identifiants",
      "done": "Je les ai copiés",
      "warning": "Nous ne pouvons pas réafficher ce jeton Bearer. Collez-le immédiatement dans la configuration SCIM de votre IdP. Si vous le perdez, renouvelez le jeton et collez-le à nouveau.",
      "scimEndpoint": "Point de terminaison SCIM",
      "bearerToken": "Jeton Bearer"
    },
    "users": {
      "title": "{count, plural, =0 {Utilisateurs synchronisés} one {# utilisateur synchronisé} other {# utilisateurs synchronisés}}",
      "loading": "Chargement des utilisateurs…",
      "empty": "Aucun utilisateur n’a encore été synchronisé. Provisionnez-en quelques-uns dans votre IdP et cliquez sur « Synchroniser maintenant ».",
      "columns": {
        "email": "E-mail",
        "name": "Nom",
        "status": "Statut",
        "lastSynced": "Dernière synchronisation"
      },
      "status": {
        "active": "actif",
        "suspended": "suspendu",
        "deactivated": "désactivé"
      }
    },
    "groups": {
      "title": "{count, plural, =0 {Groupes synchronisés} one {# groupe synchronisé} other {# groupes synchronisés}}",
      "loading": "Chargement des groupes…",
      "empty": "Aucun groupe synchronisé pour le moment. Provisionnez des groupes dans votre IdP pour remplir cette liste.",
      "columns": {
        "name": "Groupe",
        "members": "Membres",
        "lastUpdated": "Dernière mise à jour"
      }
    }
  },
  "es": {
    "title": "Sincronización de directorio",
    "subtitle": "Aprovisiona un directorio SCIM 2.0 para que el ciclo de vida de los usuarios (altas, cambios, bajas) se mantenga sincronizado con esta organización.",
    "provision": "Aprovisionar directorio",
    "empty": "Aún no hay directorios. Haz clic en «{action}» para crear uno.",
    "loading": "Cargando directorios…",
    "columns": {
      "name": "Nombre",
      "provider": "Proveedor",
      "state": "Estado",
      "lastSync": "Última sincronización"
    },
    "state": {
      "active": "activo",
      "paused": "en pausa",
      "revoked": "revocado"
    },
    "actions": {
      "users": "Usuarios",
      "syncNow": "Sincronizar ahora",
      "rotateToken": "Rotar token",
      "delete": "Eliminar",
      "groups": "Grupos"
    },
    "deleteConfirm": "¿Eliminar el directorio {name}? Esto detiene la sincronización SCIM de inmediato.",
    "form": {
      "displayName": "Nombre para mostrar",
      "displayNamePlaceholder": "Acme HQ Okta",
      "provider": "Proveedor",
      "provision": "Aprovisionar",
      "provisioning": "Aprovisionando…"
    },
    "secret": {
      "title": "Guarda estas credenciales",
      "done": "Las he copiado",
      "warning": "No podemos volver a mostrar este token Bearer. Pégalo de inmediato en la configuración SCIM de tu IdP. Si lo pierdes, rota el token y vuelve a pegarlo.",
      "scimEndpoint": "Endpoint SCIM",
      "bearerToken": "Token Bearer"
    },
    "users": {
      "title": "{count, plural, =0 {Usuarios sincronizados} one {# usuario sincronizado} other {# usuarios sincronizados}}",
      "loading": "Cargando usuarios…",
      "empty": "Aún no se ha sincronizado ningún usuario. Aprovisiona algunos en tu IdP y haz clic en «Sincronizar ahora».",
      "columns": {
        "email": "Correo electrónico",
        "name": "Nombre",
        "status": "Estado",
        "lastSynced": "Última sincronización"
      },
      "status": {
        "active": "activo",
        "suspended": "suspendido",
        "deactivated": "desactivado"
      }
    },
    "groups": {
      "title": "{count, plural, =0 {Grupos sincronizados} one {# grupo sincronizado} other {# grupos sincronizados}}",
      "loading": "Cargando grupos…",
      "empty": "Aún no hay grupos sincronizados. Provisiona grupos en tu IdP para completar esta lista.",
      "columns": {
        "name": "Grupo",
        "members": "Miembros",
        "lastUpdated": "Última actualización"
      }
    }
  },
  "ja": {
    "title": "ディレクトリ同期",
    "subtitle": "SCIM 2.0 ディレクトリをプロビジョニングして、ユーザーのライフサイクル（入社・異動・退社）をこの組織と同期させます。",
    "provision": "ディレクトリをプロビジョニング",
    "empty": "ディレクトリはまだありません。「{action}」をクリックして作成してください。",
    "loading": "ディレクトリを読み込んでいます…",
    "columns": {
      "name": "名前",
      "provider": "プロバイダー",
      "state": "状態",
      "lastSync": "最終同期"
    },
    "state": {
      "active": "有効",
      "paused": "一時停止",
      "revoked": "取り消し済み"
    },
    "actions": {
      "users": "ユーザー",
      "syncNow": "今すぐ同期",
      "rotateToken": "トークンをローテーション",
      "delete": "削除",
      "groups": "グループ"
    },
    "deleteConfirm": "ディレクトリ {name} を削除しますか？ SCIM 同期がただちに停止します。",
    "form": {
      "displayName": "表示名",
      "displayNamePlaceholder": "Acme HQ Okta",
      "provider": "プロバイダー",
      "provision": "プロビジョニング",
      "provisioning": "プロビジョニングしています…"
    },
    "secret": {
      "title": "これらの認証情報を保存してください",
      "done": "コピーしました",
      "warning": "この Bearer トークンは再表示できません。すぐに IdP の SCIM 設定に貼り付けてください。紛失した場合はトークンをローテーションして貼り直してください。",
      "scimEndpoint": "SCIM エンドポイント",
      "bearerToken": "Bearer トークン"
    },
    "users": {
      "title": "{count, plural, =0 {同期されたユーザー} other {同期されたユーザー # 人}}",
      "loading": "ユーザーを読み込んでいます…",
      "empty": "まだ同期されたユーザーはいません。IdP でいくつかプロビジョニングして「今すぐ同期」をクリックしてください。",
      "columns": {
        "email": "メール",
        "name": "名前",
        "status": "ステータス",
        "lastSynced": "最終同期"
      },
      "status": {
        "active": "有効",
        "suspended": "停止中",
        "deactivated": "無効化済み"
      }
    },
    "groups": {
      "title": "{count, plural, =0 {同期されたグループ} other {同期されたグループ # 件}}",
      "loading": "グループを読み込み中…",
      "empty": "まだグループは同期されていません。IdP でグループをプロビジョニングしてください。",
      "columns": {
        "name": "グループ",
        "members": "メンバー",
        "lastUpdated": "最終更新"
      }
    }
  },
  "pt-BR": {
    "title": "Sincronização de diretório",
    "subtitle": "Provisione um diretório SCIM 2.0 para que o ciclo de vida dos usuários (entradas, mudanças, saídas) permaneça em sincronia com esta organização.",
    "provision": "Provisionar diretório",
    "empty": "Ainda não há diretórios. Clique em \"{action}\" para criar um.",
    "loading": "Carregando diretórios…",
    "columns": {
      "name": "Nome",
      "provider": "Provedor",
      "state": "Estado",
      "lastSync": "Última sincronização"
    },
    "state": {
      "active": "ativo",
      "paused": "pausado",
      "revoked": "revogado"
    },
    "actions": {
      "users": "Usuários",
      "syncNow": "Sincronizar agora",
      "rotateToken": "Girar token",
      "delete": "Excluir",
      "groups": "Grupos"
    },
    "deleteConfirm": "Excluir o diretório {name}? Isso interrompe a sincronização SCIM imediatamente.",
    "form": {
      "displayName": "Nome de exibição",
      "displayNamePlaceholder": "Acme HQ Okta",
      "provider": "Provedor",
      "provision": "Provisionar",
      "provisioning": "Provisionando…"
    },
    "secret": {
      "title": "Salve estas credenciais",
      "done": "Eu as copiei",
      "warning": "Não podemos mostrar este token Bearer novamente. Cole-o imediatamente na configuração SCIM do seu IdP. Se você o perder, gire o token e cole-o novamente.",
      "scimEndpoint": "Endpoint SCIM",
      "bearerToken": "Token Bearer"
    },
    "users": {
      "title": "{count, plural, =0 {Usuários sincronizados} one {# usuário sincronizado} other {# usuários sincronizados}}",
      "loading": "Carregando usuários…",
      "empty": "Nenhum usuário foi sincronizado ainda. Provisione alguns no seu IdP e clique em \"Sincronizar agora\".",
      "columns": {
        "email": "E-mail",
        "name": "Nome",
        "status": "Status",
        "lastSynced": "Última sincronização"
      },
      "status": {
        "active": "ativo",
        "suspended": "suspenso",
        "deactivated": "desativado"
      }
    },
    "groups": {
      "title": "{count, plural, =0 {Grupos sincronizados} one {# grupo sincronizado} other {# grupos sincronizados}}",
      "loading": "Carregando grupos…",
      "empty": "Nenhum grupo sincronizado ainda. Provisione grupos no seu IdP para preencher esta lista.",
      "columns": {
        "name": "Grupo",
        "members": "Membros",
        "lastUpdated": "Última atualização"
      }
    }
  }
} as const;

export const auditLog: LocaleCatalog = {
  "en": {
    "title": "Audit log",
    "subtitle": "Activity log for this organization. Click a row to expand.",
    "export": "Export CSV",
    "exporting": "Exporting…",
    "loading": "Loading events…",
    "empty": "No audit events found for the current filters.",
    "filters": {
      "actor": "Actor ID",
      "actorPlaceholder": "user_abc",
      "eventType": "Event type",
      "eventTypePlaceholder": "session.created",
      "after": "After",
      "before": "Before",
      "apply": "Apply filters",
      "clear": "Clear"
    },
    "columns": {
      "time": "Time",
      "action": "Action",
      "actor": "Actor",
      "target": "Target",
      "ip": "IP"
    },
    "range": "{from}–{to} of {total, plural, one {# event} other {# events}}"
  },
  "de": {
    "title": "Audit-Protokoll",
    "subtitle": "Aktivitätsprotokoll für diese Organisation. Klicken Sie auf eine Zeile, um sie zu erweitern.",
    "export": "CSV exportieren",
    "exporting": "Wird exportiert…",
    "loading": "Ereignisse werden geladen…",
    "empty": "Für die aktuellen Filter wurden keine Audit-Ereignisse gefunden.",
    "filters": {
      "actor": "Akteur-ID",
      "actorPlaceholder": "user_abc",
      "eventType": "Ereignistyp",
      "eventTypePlaceholder": "session.created",
      "after": "Nach",
      "before": "Vor",
      "apply": "Filter anwenden",
      "clear": "Zurücksetzen"
    },
    "columns": {
      "time": "Zeit",
      "action": "Aktion",
      "actor": "Akteur",
      "target": "Ziel",
      "ip": "IP"
    },
    "range": "{from}–{to} von {total, plural, one {# Ereignis} other {# Ereignissen}}"
  },
  "fr": {
    "title": "Journal d’audit",
    "subtitle": "Journal d’activité de cette organisation. Cliquez sur une ligne pour la développer.",
    "export": "Exporter en CSV",
    "exporting": "Exportation…",
    "loading": "Chargement des événements…",
    "empty": "Aucun événement d’audit trouvé pour les filtres actuels.",
    "filters": {
      "actor": "ID d’acteur",
      "actorPlaceholder": "user_abc",
      "eventType": "Type d’événement",
      "eventTypePlaceholder": "session.created",
      "after": "Après",
      "before": "Avant",
      "apply": "Appliquer les filtres",
      "clear": "Effacer"
    },
    "columns": {
      "time": "Heure",
      "action": "Action",
      "actor": "Acteur",
      "target": "Cible",
      "ip": "IP"
    },
    "range": "{from}–{to} sur {total, plural, one {# événement} other {# événements}}"
  },
  "es": {
    "title": "Registro de auditoría",
    "subtitle": "Registro de actividad de esta organización. Haz clic en una fila para expandirla.",
    "export": "Exportar CSV",
    "exporting": "Exportando…",
    "loading": "Cargando eventos…",
    "empty": "No se encontraron eventos de auditoría para los filtros actuales.",
    "filters": {
      "actor": "ID de actor",
      "actorPlaceholder": "user_abc",
      "eventType": "Tipo de evento",
      "eventTypePlaceholder": "session.created",
      "after": "Después de",
      "before": "Antes de",
      "apply": "Aplicar filtros",
      "clear": "Limpiar"
    },
    "columns": {
      "time": "Hora",
      "action": "Acción",
      "actor": "Actor",
      "target": "Destino",
      "ip": "IP"
    },
    "range": "{from}–{to} de {total, plural, one {# evento} other {# eventos}}"
  },
  "ja": {
    "title": "監査ログ",
    "subtitle": "この組織のアクティビティログです。行をクリックすると展開します。",
    "export": "CSV をエクスポート",
    "exporting": "エクスポートしています…",
    "loading": "イベントを読み込んでいます…",
    "empty": "現在のフィルターに一致する監査イベントは見つかりませんでした。",
    "filters": {
      "actor": "アクター ID",
      "actorPlaceholder": "user_abc",
      "eventType": "イベントタイプ",
      "eventTypePlaceholder": "session.created",
      "after": "開始",
      "before": "終了",
      "apply": "フィルターを適用",
      "clear": "クリア"
    },
    "columns": {
      "time": "時刻",
      "action": "アクション",
      "actor": "アクター",
      "target": "対象",
      "ip": "IP"
    },
    "range": "{total, plural, other {# 件}}中 {from}–{to}"
  },
  "pt-BR": {
    "title": "Log de auditoria",
    "subtitle": "Log de atividade desta organização. Clique em uma linha para expandir.",
    "export": "Exportar CSV",
    "exporting": "Exportando…",
    "loading": "Carregando eventos…",
    "empty": "Nenhum evento de auditoria encontrado para os filtros atuais.",
    "filters": {
      "actor": "ID do ator",
      "actorPlaceholder": "user_abc",
      "eventType": "Tipo de evento",
      "eventTypePlaceholder": "session.created",
      "after": "Depois de",
      "before": "Antes de",
      "apply": "Aplicar filtros",
      "clear": "Limpar"
    },
    "columns": {
      "time": "Horário",
      "action": "Ação",
      "actor": "Ator",
      "target": "Alvo",
      "ip": "IP"
    },
    "range": "{from}–{to} de {total, plural, one {# evento} other {# eventos}}"
  }
} as const;

export const apiKeys: LocaleCatalog = {
  "en": {
    "title": "API keys",
    "subtitle": "Manage API keys for this project. Revoked keys stop working immediately.",
    "create": "Create key",
    "loading": "Loading keys…",
    "empty": "No API keys yet. Create one above.",
    "columns": {
      "name": "Name",
      "prefix": "Prefix",
      "created": "Created",
      "lastUsed": "Last used"
    },
    "revoke": "Revoke",
    "revokeConfirm": "Revoke key \"{name}\"? This cannot be undone.",
    "reveal": {
      "badge": "Key created",
      "warning": "Copy this key now — it won't be shown again.",
      "saved": "I've saved it"
    },
    "form": {
      "name": "Key name",
      "namePlaceholder": "Production key",
      "scopes": "Scopes (optional, space-separated)",
      "scopesPlaceholder": "read write",
      "expiry": "Expires in (days, optional)",
      "expiryPlaceholder": "90",
      "create": "Create key",
      "creating": "Creating…"
    }
  },
  "de": {
    "title": "API-Schlüssel",
    "subtitle": "Verwalten Sie API-Schlüssel für dieses Projekt. Widerrufene Schlüssel funktionieren sofort nicht mehr.",
    "create": "Schlüssel erstellen",
    "loading": "Schlüssel werden geladen…",
    "empty": "Noch keine API-Schlüssel. Erstellen Sie oben einen.",
    "columns": {
      "name": "Name",
      "prefix": "Präfix",
      "created": "Erstellt",
      "lastUsed": "Zuletzt verwendet"
    },
    "revoke": "Widerrufen",
    "revokeConfirm": "Schlüssel „{name}“ widerrufen? Dies kann nicht rückgängig gemacht werden.",
    "reveal": {
      "badge": "Schlüssel erstellt",
      "warning": "Kopieren Sie diesen Schlüssel jetzt — er wird nicht erneut angezeigt.",
      "saved": "Ich habe ihn gespeichert"
    },
    "form": {
      "name": "Schlüsselname",
      "namePlaceholder": "Produktionsschlüssel",
      "scopes": "Berechtigungen (optional, durch Leerzeichen getrennt)",
      "scopesPlaceholder": "read write",
      "expiry": "Läuft ab in (Tagen, optional)",
      "expiryPlaceholder": "90",
      "create": "Schlüssel erstellen",
      "creating": "Wird erstellt…"
    }
  },
  "fr": {
    "title": "Clés API",
    "subtitle": "Gérez les clés API de ce projet. Les clés révoquées cessent immédiatement de fonctionner.",
    "create": "Créer une clé",
    "loading": "Chargement des clés…",
    "empty": "Aucune clé API pour le moment. Créez-en une ci-dessus.",
    "columns": {
      "name": "Nom",
      "prefix": "Préfixe",
      "created": "Créée",
      "lastUsed": "Dernière utilisation"
    },
    "revoke": "Révoquer",
    "revokeConfirm": "Révoquer la clé « {name} » ? Cette action est irréversible.",
    "reveal": {
      "badge": "Clé créée",
      "warning": "Copiez cette clé maintenant — elle ne sera plus affichée.",
      "saved": "Je l’ai enregistrée"
    },
    "form": {
      "name": "Nom de la clé",
      "namePlaceholder": "Clé de production",
      "scopes": "Portées (facultatif, séparées par des espaces)",
      "scopesPlaceholder": "read write",
      "expiry": "Expire dans (jours, facultatif)",
      "expiryPlaceholder": "90",
      "create": "Créer une clé",
      "creating": "Création…"
    }
  },
  "es": {
    "title": "Claves API",
    "subtitle": "Administra las claves API de este proyecto. Las claves revocadas dejan de funcionar de inmediato.",
    "create": "Crear clave",
    "loading": "Cargando claves…",
    "empty": "Aún no hay claves API. Crea una arriba.",
    "columns": {
      "name": "Nombre",
      "prefix": "Prefijo",
      "created": "Creada",
      "lastUsed": "Último uso"
    },
    "revoke": "Revocar",
    "revokeConfirm": "¿Revocar la clave «{name}»? Esta acción no se puede deshacer.",
    "reveal": {
      "badge": "Clave creada",
      "warning": "Copia esta clave ahora — no se volverá a mostrar.",
      "saved": "La he guardado"
    },
    "form": {
      "name": "Nombre de la clave",
      "namePlaceholder": "Clave de producción",
      "scopes": "Alcances (opcional, separados por espacios)",
      "scopesPlaceholder": "read write",
      "expiry": "Caduca en (días, opcional)",
      "expiryPlaceholder": "90",
      "create": "Crear clave",
      "creating": "Creando…"
    }
  },
  "ja": {
    "title": "API キー",
    "subtitle": "このプロジェクトの API キーを管理します。取り消したキーはただちに使用できなくなります。",
    "create": "キーを作成",
    "loading": "キーを読み込んでいます…",
    "empty": "API キーはまだありません。上で作成してください。",
    "columns": {
      "name": "名前",
      "prefix": "プレフィックス",
      "created": "作成日",
      "lastUsed": "最終使用"
    },
    "revoke": "取り消し",
    "revokeConfirm": "キー「{name}」を取り消しますか？ この操作は取り消せません。",
    "reveal": {
      "badge": "キーを作成しました",
      "warning": "このキーを今すぐコピーしてください。再表示されません。",
      "saved": "保存しました"
    },
    "form": {
      "name": "キー名",
      "namePlaceholder": "本番キー",
      "scopes": "スコープ（任意、スペース区切り）",
      "scopesPlaceholder": "read write",
      "expiry": "有効期限（日数、任意）",
      "expiryPlaceholder": "90",
      "create": "キーを作成",
      "creating": "作成しています…"
    }
  },
  "pt-BR": {
    "title": "Chaves de API",
    "subtitle": "Gerencie as chaves de API deste projeto. Chaves revogadas param de funcionar imediatamente.",
    "create": "Criar chave",
    "loading": "Carregando chaves…",
    "empty": "Ainda não há chaves de API. Crie uma acima.",
    "columns": {
      "name": "Nome",
      "prefix": "Prefixo",
      "created": "Criada",
      "lastUsed": "Último uso"
    },
    "revoke": "Revogar",
    "revokeConfirm": "Revogar a chave \"{name}\"? Isso não pode ser desfeito.",
    "reveal": {
      "badge": "Chave criada",
      "warning": "Copie esta chave agora — ela não será exibida novamente.",
      "saved": "Eu a salvei"
    },
    "form": {
      "name": "Nome da chave",
      "namePlaceholder": "Chave de produção",
      "scopes": "Escopos (opcional, separados por espaços)",
      "scopesPlaceholder": "read write",
      "expiry": "Expira em (dias, opcional)",
      "expiryPlaceholder": "90",
      "create": "Criar chave",
      "creating": "Criando…"
    }
  }
} as const;

export const userSessions: LocaleCatalog = {
  "en": {
    "title": "Active sessions",
    "subtitle": "Your active sign-in sessions. Revoke any you don't recognize.",
    "revokeAll": "Revoke all sessions",
    "revokeAllConfirm": "Revoke all sessions? You'll be signed out everywhere.",
    "loading": "Loading sessions…",
    "empty": "No active sessions found.",
    "columns": {
      "device": "Device / browser",
      "ip": "IP",
      "location": "Location",
      "lastActive": "Last active"
    },
    "unknownBrowser": "Unknown browser",
    "revoke": "Revoke",
    "revokeConfirm": "Revoke this session?"
  },
  "de": {
    "title": "Aktive Sitzungen",
    "subtitle": "Ihre aktiven Anmeldesitzungen. Widerrufen Sie alle, die Sie nicht erkennen.",
    "revokeAll": "Alle Sitzungen widerrufen",
    "revokeAllConfirm": "Alle Sitzungen widerrufen? Sie werden überall abgemeldet.",
    "loading": "Sitzungen werden geladen…",
    "empty": "Keine aktiven Sitzungen gefunden.",
    "columns": {
      "device": "Gerät / Browser",
      "ip": "IP",
      "location": "Standort",
      "lastActive": "Zuletzt aktiv"
    },
    "unknownBrowser": "Unbekannter Browser",
    "revoke": "Widerrufen",
    "revokeConfirm": "Diese Sitzung widerrufen?"
  },
  "fr": {
    "title": "Sessions actives",
    "subtitle": "Vos sessions de connexion actives. Révoquez celles que vous ne reconnaissez pas.",
    "revokeAll": "Révoquer toutes les sessions",
    "revokeAllConfirm": "Révoquer toutes les sessions ? Vous serez déconnecté partout.",
    "loading": "Chargement des sessions…",
    "empty": "Aucune session active trouvée.",
    "columns": {
      "device": "Appareil / navigateur",
      "ip": "IP",
      "location": "Emplacement",
      "lastActive": "Dernière activité"
    },
    "unknownBrowser": "Navigateur inconnu",
    "revoke": "Révoquer",
    "revokeConfirm": "Révoquer cette session ?"
  },
  "es": {
    "title": "Sesiones activas",
    "subtitle": "Tus sesiones de inicio activas. Revoca las que no reconozcas.",
    "revokeAll": "Revocar todas las sesiones",
    "revokeAllConfirm": "¿Revocar todas las sesiones? Se cerrará tu sesión en todas partes.",
    "loading": "Cargando sesiones…",
    "empty": "No se encontraron sesiones activas.",
    "columns": {
      "device": "Dispositivo / navegador",
      "ip": "IP",
      "location": "Ubicación",
      "lastActive": "Última actividad"
    },
    "unknownBrowser": "Navegador desconocido",
    "revoke": "Revocar",
    "revokeConfirm": "¿Revocar esta sesión?"
  },
  "ja": {
    "title": "アクティブなセッション",
    "subtitle": "現在ログイン中のセッションです。心当たりのないものは取り消してください。",
    "revokeAll": "すべてのセッションを取り消す",
    "revokeAllConfirm": "すべてのセッションを取り消しますか？ すべての場所からサインアウトされます。",
    "loading": "セッションを読み込んでいます…",
    "empty": "アクティブなセッションは見つかりませんでした。",
    "columns": {
      "device": "デバイス / ブラウザ",
      "ip": "IP",
      "location": "場所",
      "lastActive": "最終アクティブ"
    },
    "unknownBrowser": "不明なブラウザ",
    "revoke": "取り消し",
    "revokeConfirm": "このセッションを取り消しますか？"
  },
  "pt-BR": {
    "title": "Sessões ativas",
    "subtitle": "Suas sessões de login ativas. Revogue qualquer uma que você não reconheça.",
    "revokeAll": "Revogar todas as sessões",
    "revokeAllConfirm": "Revogar todas as sessões? Você será desconectado em todos os lugares.",
    "loading": "Carregando sessões…",
    "empty": "Nenhuma sessão ativa encontrada.",
    "columns": {
      "device": "Dispositivo / navegador",
      "ip": "IP",
      "location": "Local",
      "lastActive": "Última atividade"
    },
    "unknownBrowser": "Navegador desconhecido",
    "revoke": "Revogar",
    "revokeConfirm": "Revogar esta sessão?"
  }
} as const;

export const organizationSwitcher: LocaleCatalog = {
  "en": {
    "loading": "Loading…",
    "select": "Select organization",
    "empty": "No organizations found.",
    "addOrganization": "Add organization",
    "ariaLabel": "Organizations"
  },
  "de": {
    "loading": "Wird geladen…",
    "select": "Organisation auswählen",
    "empty": "Keine Organisationen gefunden.",
    "addOrganization": "Organisation hinzufügen",
    "ariaLabel": "Organisationen"
  },
  "fr": {
    "loading": "Chargement…",
    "select": "Sélectionner une organisation",
    "empty": "Aucune organisation trouvée.",
    "addOrganization": "Ajouter une organisation",
    "ariaLabel": "Organisations"
  },
  "es": {
    "loading": "Cargando…",
    "select": "Seleccionar organización",
    "empty": "No se encontraron organizaciones.",
    "addOrganization": "Añadir organización",
    "ariaLabel": "Organizaciones"
  },
  "ja": {
    "loading": "読み込んでいます…",
    "select": "組織を選択",
    "empty": "組織が見つかりませんでした。",
    "addOrganization": "組織を追加",
    "ariaLabel": "組織"
  },
  "pt-BR": {
    "loading": "Carregando…",
    "select": "Selecionar organização",
    "empty": "Nenhuma organização encontrada.",
    "addOrganization": "Adicionar organização",
    "ariaLabel": "Organizações"
  }
} as const;

export const pipes: LocaleCatalog = {
  "en": {
    "title": "Connected Accounts",
    "subtitle": "Connect your accounts to allow this app to act on your behalf.",
    "connect": "Connect",
    "connectAria": "Connect {provider}",
    "disconnect": "Disconnect",
    "disconnectAria": "Disconnect {provider}",
    "disconnecting": "Disconnecting…",
    "connected": "Connected",
    "connectedWith": "Connected · {email}",
    "errorFallback": "Failed to load connected accounts.",
    "retry": "Retry"
  },
  "de": {
    "title": "Verbundene Konten",
    "subtitle": "Verbinden Sie Ihre Konten, damit diese App in Ihrem Namen handeln kann.",
    "connect": "Verbinden",
    "connectAria": "{provider} verbinden",
    "disconnect": "Trennen",
    "disconnectAria": "{provider} trennen",
    "disconnecting": "Wird getrennt…",
    "connected": "Verbunden",
    "connectedWith": "Verbunden · {email}",
    "errorFallback": "Verbundene Konten konnten nicht geladen werden.",
    "retry": "Erneut versuchen"
  },
  "fr": {
    "title": "Comptes connectés",
    "subtitle": "Connectez vos comptes pour autoriser cette application à agir en votre nom.",
    "connect": "Connecter",
    "connectAria": "Connecter {provider}",
    "disconnect": "Déconnecter",
    "disconnectAria": "Déconnecter {provider}",
    "disconnecting": "Déconnexion…",
    "connected": "Connecté",
    "connectedWith": "Connecté · {email}",
    "errorFallback": "Impossible de charger les comptes connectés.",
    "retry": "Réessayer"
  },
  "es": {
    "title": "Cuentas conectadas",
    "subtitle": "Conecta tus cuentas para permitir que esta app actúe en tu nombre.",
    "connect": "Conectar",
    "connectAria": "Conectar {provider}",
    "disconnect": "Desconectar",
    "disconnectAria": "Desconectar {provider}",
    "disconnecting": "Desconectando…",
    "connected": "Conectado",
    "connectedWith": "Conectado · {email}",
    "errorFallback": "No se pudieron cargar las cuentas conectadas.",
    "retry": "Reintentar"
  },
  "ja": {
    "title": "接続済みアカウント",
    "subtitle": "アカウントを接続して、このアプリがあなたの代わりに操作できるようにします。",
    "connect": "接続",
    "connectAria": "{provider} を接続",
    "disconnect": "切断",
    "disconnectAria": "{provider} を切断",
    "disconnecting": "切断しています…",
    "connected": "接続済み",
    "connectedWith": "接続済み · {email}",
    "errorFallback": "接続済みアカウントを読み込めませんでした。",
    "retry": "再試行"
  },
  "pt-BR": {
    "title": "Contas conectadas",
    "subtitle": "Conecte suas contas para permitir que este app aja em seu nome.",
    "connect": "Conectar",
    "connectAria": "Conectar {provider}",
    "disconnect": "Desconectar",
    "disconnectAria": "Desconectar {provider}",
    "disconnecting": "Desconectando…",
    "connected": "Conectado",
    "connectedWith": "Conectado · {email}",
    "errorFallback": "Não foi possível carregar as contas conectadas.",
    "retry": "Tentar novamente"
  }
} as const;

export const error: LocaleCatalog = {
  "en": {
    "network_error": "Couldn't reach the server. Check your connection and try again.",
    "widget_origin_mismatch": "This widget isn't authorized to run on this site.",
    "widget_token_expired": "Your session expired. Reload the page to continue.",
    "widget_token_revoked": "Access was revoked. Reload the page to continue.",
    "widget_scope_required": "This action isn't permitted for this widget.",
    "missing_token": "This widget is missing its access token.",
    "missing_organization_id": "This widget is missing an organization id.",
    "load_failed": "Something went wrong while loading. Please try again.",
    "connect_failed": "Couldn't start the connection. Please try again.",
    "revoke_failed": "Couldn't disconnect that account. Please try again.",
    "client_error": "Something went wrong. Please try again.",
    "unknown": "Something went wrong. Please try again."
  },
  "de": {
    "network_error": "Der Server ist nicht erreichbar. Überprüfen Sie Ihre Verbindung und versuchen Sie es erneut.",
    "widget_origin_mismatch": "Dieses Widget ist für diese Website nicht autorisiert.",
    "widget_token_expired": "Ihre Sitzung ist abgelaufen. Laden Sie die Seite neu, um fortzufahren.",
    "widget_token_revoked": "Der Zugriff wurde widerrufen. Laden Sie die Seite neu, um fortzufahren.",
    "widget_scope_required": "Diese Aktion ist für dieses Widget nicht zulässig.",
    "missing_token": "Diesem Widget fehlt sein Zugriffstoken.",
    "missing_organization_id": "Diesem Widget fehlt eine Organisations-ID.",
    "load_failed": "Beim Laden ist etwas schiefgelaufen. Bitte versuchen Sie es erneut.",
    "connect_failed": "Die Verbindung konnte nicht gestartet werden. Bitte versuchen Sie es erneut.",
    "revoke_failed": "Dieses Konto konnte nicht getrennt werden. Bitte versuchen Sie es erneut.",
    "client_error": "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut.",
    "unknown": "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut."
  },
  "fr": {
    "network_error": "Impossible de joindre le serveur. Vérifiez votre connexion et réessayez.",
    "widget_origin_mismatch": "Ce widget n’est pas autorisé sur ce site.",
    "widget_token_expired": "Votre session a expiré. Rechargez la page pour continuer.",
    "widget_token_revoked": "L’accès a été révoqué. Rechargez la page pour continuer.",
    "widget_scope_required": "Cette action n’est pas autorisée pour ce widget.",
    "missing_token": "Ce widget n’a pas de jeton d’accès.",
    "missing_organization_id": "Ce widget n’a pas d’identifiant d’organisation.",
    "load_failed": "Une erreur s’est produite lors du chargement. Veuillez réessayer.",
    "connect_failed": "Impossible de démarrer la connexion. Veuillez réessayer.",
    "revoke_failed": "Impossible de déconnecter ce compte. Veuillez réessayer.",
    "client_error": "Une erreur s’est produite. Veuillez réessayer.",
    "unknown": "Une erreur s’est produite. Veuillez réessayer."
  },
  "es": {
    "network_error": "No se pudo conectar con el servidor. Comprueba tu conexión e inténtalo de nuevo.",
    "widget_origin_mismatch": "Este widget no está autorizado en este sitio.",
    "widget_token_expired": "Tu sesión ha expirado. Recarga la página para continuar.",
    "widget_token_revoked": "Se revocó el acceso. Recarga la página para continuar.",
    "widget_scope_required": "Esta acción no está permitida para este widget.",
    "missing_token": "A este widget le falta su token de acceso.",
    "missing_organization_id": "A este widget le falta un id de organización.",
    "load_failed": "Algo salió mal al cargar. Inténtalo de nuevo.",
    "connect_failed": "No se pudo iniciar la conexión. Inténtalo de nuevo.",
    "revoke_failed": "No se pudo desconectar esa cuenta. Inténtalo de nuevo.",
    "client_error": "Algo salió mal. Inténtalo de nuevo.",
    "unknown": "Algo salió mal. Inténtalo de nuevo."
  },
  "ja": {
    "network_error": "サーバーに接続できませんでした。接続を確認して再試行してください。",
    "widget_origin_mismatch": "このウィジェットはこのサイトでの利用を許可されていません。",
    "widget_token_expired": "セッションの有効期限が切れました。ページを再読み込みして続行してください。",
    "widget_token_revoked": "アクセスが取り消されました。ページを再読み込みして続行してください。",
    "widget_scope_required": "この操作はこのウィジェットでは許可されていません。",
    "missing_token": "このウィジェットにはアクセストークンがありません。",
    "missing_organization_id": "このウィジェットには組織 ID がありません。",
    "load_failed": "読み込み中に問題が発生しました。もう一度お試しください。",
    "connect_failed": "接続を開始できませんでした。もう一度お試しください。",
    "revoke_failed": "そのアカウントを切断できませんでした。もう一度お試しください。",
    "client_error": "問題が発生しました。もう一度お試しください。",
    "unknown": "問題が発生しました。もう一度お試しください。"
  },
  "pt-BR": {
    "network_error": "Não foi possível acessar o servidor. Verifique sua conexão e tente novamente.",
    "widget_origin_mismatch": "Este widget não está autorizado neste site.",
    "widget_token_expired": "Sua sessão expirou. Recarregue a página para continuar.",
    "widget_token_revoked": "O acesso foi revogado. Recarregue a página para continuar.",
    "widget_scope_required": "Esta ação não é permitida para este widget.",
    "missing_token": "Este widget está sem o token de acesso.",
    "missing_organization_id": "Este widget está sem um id de organização.",
    "load_failed": "Algo deu errado ao carregar. Tente novamente.",
    "connect_failed": "Não foi possível iniciar a conexão. Tente novamente.",
    "revoke_failed": "Não foi possível desconectar essa conta. Tente novamente.",
    "client_error": "Algo deu errado. Tente novamente.",
    "unknown": "Algo deu errado. Tente novamente."
  }
} as const;
